version: '3.8'

networks:
  rescue-net:
    name: rescue-net

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    networks:
      - rescue-net
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
