version: '3.8'

networks:
  rescue-net:
    name: rescue-net

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,sns,sqs
      - AWS_DEFAULT_REGION=ap-southeast-1
    networks:
      - rescue-net
